name: fiber
description: A Portal App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  graphql_flutter: ^3.0.0
  webfeed: ^0.4.2
  cupertino_icons: ^0.1.2
  get_it: ^3.0.3
  http: "^0.12.0+1"
  url_launcher: ^5.4.5
  flutter_svg: ^0.17.4
  youtube_player_flutter: ^6.1.1
  flutter_web_auth: ^0.2.4
  shared_preferences: ^0.5.8
  jwt_decoder: ^1.0.1
  cached_network_image: ^2.2.0+1
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  equatable:

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600